### ISSUE TITLE
Get working instance booting from vagrant in one command

### ISSUE THREAD

**Issue by patcon** [designcofounders/toronto-city-hall-api#7]
Currently I'm getting an error that's telling me that `keys/namara` is missing when trying to run `sails www`

Might not be a blocker, but ran into it while trying to run through the current setup and get it booting from a vagrantfile. I'm getting another error in my VM during migration, and so was trying to do `sails www` as an intermediary step as a sanity check, and came across the mentioned error.

A little tangential, but I'd love to get a vagrantfile booting and exercising the whole process from nothing, so while I'm using the db dump now, i'd rather have it build from the sources, so that we know ASAP if that process breaks. I'll work on getting it going for the db dump for now, but afterward, I was thinking about building the db with pupa. Any thoughts?

Also, if you felt like it, it might be helpful to blow your VM away with regularity, and see if you can bring it back by explicitly following your own instructions? And related to that, if I set up a vagrantfile, would that be something you might use? It's more useful if everyone is putting it through its paces, if you know what I mean :)
#### TODO
- [x] get MVP working
- [ ] daemonize
- [ ] get pupa scraping happening? (no starter db required)

**Comment by dougestey** [comment]
I [pushed an update](https://github.com/designcofounders/toronto-city-hall-api/commit/f4cea669ec39992bf018fca0bfea4a53129b3802) which stuffs the check for keys into a try/catch, so that error you're getting on startup should be resolved. I also [updated the readme](https://github.com/designcofounders/toronto-city-hall-api/commit/a9c00eb03be2c2e763b5fa891c00ff51ed6a6744) to specify that a pupa DB is needed at this time.

If you wish to vagrantify this process, I'm all for it. :)

**Comment by patcon** [comment]
Working on this in #9
